'use client';

import { useMemo, useState } from 'react';
import { Loader2, Sparkles, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { CharacterLibraryItem } from '@/lib/types/character-library';

interface CharacterAutoGenerateDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onCreated: (item: CharacterLibraryItem) => void;
}

const TYPE_OPTIONS: Array<{ value: CharacterLibraryItem['type']; label: string }> = [
  { value: 'character', label: '角色' },
  { value: 'product', label: '商品' },
  { value: 'environment', label: '環境' },
  { value: 'style', label: '風格' },
];

export function CharacterAutoGenerateDialog({
  isOpen,
  onClose,
  onCreated,
}: CharacterAutoGenerateDialogProps) {
  const [name, setName] = useState('');
  const [type, setType] = useState<CharacterLibraryItem['type']>('character');
  const [prompt, setPrompt] = useState('');
  const [styleHint, setStyleHint] = useState('');
  const [tagsText, setTagsText] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const parsedTags = useMemo(() => {
    const parts = tagsText
      .split(',')
      .map((tag) => tag.trim())
      .filter(Boolean);
    return [...new Set(parts)].slice(0, 12);
  }, [tagsText]);

  const handleClose = () => {
    if (isGenerating) return;
    setError(null);
    onClose();
  };

  const handleSubmit = async () => {
    if (!name.trim() || !prompt.trim()) return;
    setIsGenerating(true);
    setError(null);

    try {
      const response = await fetch('/api/data/character-library/auto-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: name.trim(),
          type,
          prompt: prompt.trim(),
          styleHint: styleHint.trim() || undefined,
          tags: parsedTags,
        }),
      });

      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload?.error || '生成失敗');
      }

      onCreated(payload.data as CharacterLibraryItem);
      setName('');
      setType('character');
      setPrompt('');
      setStyleHint('');
      setTagsText('');
      setError(null);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : '生成失敗');
    } finally {
      setIsGenerating(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[220] flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm">
      <div className="surface-panel w-full max-w-2xl border border-white/90 p-6 dark:border-white/10">
        <div className="mb-5 flex items-start justify-between">
          <div>
            <p className="text-kicker">AI Character</p>
            <h2 className="mt-2 text-2xl font-semibold tracking-tight">AI 生成角色並存入角色庫</h2>
            <p className="mt-1 text-sm text-muted-foreground">會自動生成首張參考圖並建立角色資料。</p>
          </div>
          <button
            onClick={handleClose}
            disabled={isGenerating}
            className="rounded-full border border-border/70 bg-white/70 p-2 text-slate-600 transition-colors hover:bg-white hover:text-slate-900 disabled:cursor-not-allowed disabled:opacity-60 dark:bg-slate-900/65 dark:text-slate-300"
            aria-label="關閉"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="mb-1.5 block text-sm font-medium text-muted-foreground">名稱 *</label>
              <input
                type="text"
                value={name}
                onChange={(event) => setName(event.target.value)}
                placeholder="例：都市上班族男主"
                className="w-full rounded-xl border border-border/80 bg-white/75 px-3.5 py-2.5 text-sm text-foreground focus:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring/30 dark:bg-slate-900/65"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-sm font-medium text-muted-foreground">類型 *</label>
              <select
                value={type}
                onChange={(event) => setType(event.target.value as CharacterLibraryItem['type'])}
                className="w-full rounded-xl border border-border/80 bg-white/75 px-3.5 py-2.5 text-sm text-foreground focus:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring/30 dark:bg-slate-900/65"
              >
                {TYPE_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-muted-foreground">角色描述 *</label>
            <textarea
              value={prompt}
              onChange={(event) => setPrompt(event.target.value)}
              placeholder="例：30 歲亞洲男性，俐落短髮，商務休閒穿搭，親和但專業，白底全身站姿"
              rows={4}
              className="w-full resize-none rounded-xl border border-border/80 bg-white/75 px-3.5 py-2.5 text-sm text-foreground focus:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring/30 dark:bg-slate-900/65"
            />
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-muted-foreground">風格提示（選填）</label>
            <input
              type="text"
              value={styleHint}
              onChange={(event) => setStyleHint(event.target.value)}
              placeholder="例：cinematic soft light, realistic skin texture"
              className="w-full rounded-xl border border-border/80 bg-white/75 px-3.5 py-2.5 text-sm text-foreground focus:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring/30 dark:bg-slate-900/65"
            />
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-muted-foreground">標籤（選填）</label>
            <input
              type="text"
              value={tagsText}
              onChange={(event) => setTagsText(event.target.value)}
              placeholder="例：通用, 都市, 真人（用逗號分隔）"
              className="w-full rounded-xl border border-border/80 bg-white/75 px-3.5 py-2.5 text-sm text-foreground focus:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring/30 dark:bg-slate-900/65"
            />
          </div>

          {error && (
            <div className="rounded-xl border border-rose-300/60 bg-rose-50 px-3 py-2 text-sm text-rose-700 dark:border-rose-700/40 dark:bg-rose-950/30 dark:text-rose-300">
              {error}
            </div>
          )}

          <div className="flex items-center justify-between border-t border-border/60 pt-4">
            <p className="text-xs text-muted-foreground">
              生成需要約 30-90 秒，完成後會自動加入角色庫。
            </p>
            <div className="flex items-center gap-3">
              <Button variant="outline" onClick={handleClose} disabled={isGenerating}>
                取消
              </Button>
              <Button onClick={handleSubmit} disabled={isGenerating || !name.trim() || !prompt.trim()}>
                {isGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    生成中...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    AI 生成並存入
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
