'use client';

import { useState, useEffect } from 'react';
import { characterLibraryStorage } from '@/lib/db/character-library-storage';
import { resolveCharacterViewPreviewUrl, type CharacterLibraryItem } from '@/lib/types/character-library';
import { Button } from '@/components/ui/button';
import { Plus, Search, Trash2, Edit, Image as ImageIcon, Sparkles } from 'lucide-react';
import Link from 'next/link';
import { CharacterCreateDialog } from '@/components/character-library/CharacterCreateDialog';
import { CharacterAutoGenerateDialog } from '@/components/character-library/CharacterAutoGenerateDialog';

export default function CharacterLibraryPage() {
  const [characters, setCharacters] = useState<CharacterLibraryItem[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState<'all' | CharacterLibraryItem['type']>('all');
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [editingCharacter, setEditingCharacter] = useState<CharacterLibraryItem | undefined>();

  useEffect(() => {
    void loadCharacters();
  }, []);

  const loadCharacters = async () => {
    const items = await characterLibraryStorage.getAll();
    setCharacters(items);
  };

  const filteredCharacters = characters.filter(char => {
    const matchesSearch = searchQuery === '' ||
      char.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      char.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()));

    const matchesType = filterType === 'all' || char.type === filterType;

    return matchesSearch && matchesType;
  });

  const handleDelete = (id: string) => {
    if (confirm('確定要刪除此角色？此操作無法撤銷。')) {
      void (async () => {
        await characterLibraryStorage.delete(id);
        await loadCharacters();
      })();
    }
  };

  const handleSave = (character: Omit<CharacterLibraryItem, 'id' | 'createdAt' | 'updatedAt' | 'usageCount'>) => {
    void (async () => {
      if (editingCharacter) {
        await characterLibraryStorage.update(editingCharacter.id, character);
      } else {
        await characterLibraryStorage.add(character);
      }
      await loadCharacters();
      setShowCreateDialog(false);
      setEditingCharacter(undefined);
    })();
  };

  const handleEdit = (character: CharacterLibraryItem) => {
    setEditingCharacter(character);
    setShowCreateDialog(true);
  };

  const handleCloseDialog = () => {
    setShowCreateDialog(false);
    setEditingCharacter(undefined);
  };

  const typeOptions = [
    { value: 'all', label: '全部', count: characters.length },
    { value: 'character', label: '角色', count: characters.filter(c => c.type === 'character').length },
    { value: 'product', label: '商品', count: characters.filter(c => c.type === 'product').length },
    { value: 'environment', label: '環境', count: characters.filter(c => c.type === 'environment').length },
    { value: 'style', label: '風格', count: characters.filter(c => c.type === 'style').length },
  ];

  return (
    <>
      <header className="app-header">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-kicker">Character Library</p>
              <h1 className="mt-2 text-2xl font-semibold tracking-tight">角色庫</h1>
              <p className="mt-1 text-sm text-muted-foreground">
                管理可重複使用的 IP 角色、商品與風格參考
              </p>
            </div>
            <Link href="/">
              <Button variant="outline" size="sm">
                返回首頁
              </Button>
            </Link>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <div className="max-w-7xl mx-auto">
          {/* 工具栏 */}
          <div className="surface-panel mb-6 space-y-4 p-5">
            <div className="flex items-center gap-3">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                <input
                  type="text"
                  placeholder="搜尋角色名稱或標籤..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full rounded-xl border border-border/80 bg-white/72 py-2.5 pl-10 pr-4 text-sm text-foreground shadow-[0_10px_24px_-18px_rgba(15,23,42,0.5)] backdrop-blur-lg focus:outline-none focus:ring-2 focus:ring-ring/30 focus:border-primary/40 dark:bg-slate-900/65"
                />
              </div>
              <Button variant="outline" onClick={() => setShowAutoGenerateDialog(true)}>
                <Sparkles className="w-4 h-4 mr-2" />
                AI 生成角色
              </Button>
              <Button onClick={() => setShowCreateDialog(true)}>
                <Plus className="w-4 h-4 mr-2" />
                新增角色
              </Button>
            </div>

            {/* 類型篩選 */}
            <div className="flex gap-2">
              {typeOptions.map(opt => (
                <button
                  key={opt.value}
                  onClick={() => setFilterType(opt.value as typeof filterType)}
                  className={`
                    rounded-full border px-4 py-2 text-sm font-medium transition-all
                    ${filterType === opt.value
                      ? 'border-primary/20 bg-primary text-primary-foreground shadow-[0_14px_26px_-18px_hsl(var(--primary)/0.95)]'
                      : 'border-border/70 bg-white/65 text-slate-700 hover:border-primary/25 hover:text-primary dark:bg-slate-900/60 dark:text-slate-300'
                    }
                  `}
                >
                  {opt.label} {opt.count > 0 && `(${opt.count})`}
                </button>
              ))}
            </div>
          </div>

          {/* 角色列表 */}
          {filteredCharacters.length === 0 ? (
            <div className="surface-panel py-16 text-center">
              <ImageIcon className="w-16 h-16 mx-auto text-slate-300 dark:text-slate-600 mb-4" />
              <h3 className="text-lg font-semibold text-slate-700 dark:text-slate-300 mb-2">
                {searchQuery || filterType !== 'all' ? '沒有找到匹配的角色' : '角色庫為空'}
              </h3>
              <p className="text-sm text-slate-500 dark:text-slate-400 mb-4">
                {searchQuery || filterType !== 'all'
                  ? '嘗試調整搜尋條件或篩選器'
                  : '點擊「新增角色」按鈕開始新增可重複使用的 IP 角色'
                }
              </p>
              {!searchQuery && filterType === 'all' && (
                <Button onClick={() => setShowCreateDialog(true)}>
                  <Plus className="w-4 h-4 mr-2" />
                  新增第一個角色
                </Button>
              )}
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredCharacters.map(character => (
                <CharacterCard
                  key={character.id}
                  character={character}
                  onDelete={handleDelete}
                  onEdit={() => handleEdit(character)}
                />
              ))}
            </div>
          )}
        </div>
      </main>

      {/* 建立/編輯角色對話框 */}
      <CharacterCreateDialog
        isOpen={showCreateDialog}
        onClose={handleCloseDialog}
        onSave={handleSave}
        editingCharacter={editingCharacter}
      />
      <CharacterAutoGenerateDialog
        isOpen={showAutoGenerateDialog}
        onClose={() => setShowAutoGenerateDialog(false)}
        onCreated={() => {
          void loadCharacters();
          setShowAutoGenerateDialog(false);
        }}
      />
    </>
  );
}

function CharacterCard({
  character,
  onDelete,
  onEdit
}: {
  character: CharacterLibraryItem;
  onDelete: (id: string) => void;
  onEdit: (id: string) => void;
}) {
  const frontView = character.views.find(v => v.angle === 'front') || character.views[0];

  const typeColors = {
    character: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300',
    product: 'bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300',
    environment: 'bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300',
    style: 'bg-amber-100 text-amber-700 dark:bg-amber-900 dark:text-amber-300',
  };

  return (
    <div className="surface-panel overflow-hidden transition-all duration-300 hover:-translate-y-1 hover:border-primary/25">
      {/* 主圖 */}
      {frontView && (
        <div className="relative aspect-video bg-slate-100 dark:bg-slate-900">
          <img
            src={resolveCharacterViewPreviewUrl(frontView)}
            alt={character.name}
            className="w-full h-full object-cover"
          />
          <div className="absolute top-2 right-2 flex gap-1">
            <button
              onClick={() => onEdit(character.id)}
              className="rounded-lg bg-white/90 p-1.5 transition-colors hover:bg-white"
            >
              <Edit className="w-4 h-4 text-slate-700" />
            </button>
            <button
              onClick={() => onDelete(character.id)}
              className="rounded-lg bg-white/90 p-1.5 transition-colors hover:bg-white"
            >
              <Trash2 className="w-4 h-4 text-red-600" />
            </button>
          </div>
        </div>
      )}

      {/* 資訊 */}
      <div className="p-4">
        <div className="flex items-start justify-between mb-2">
          <h3 className="font-semibold text-lg">{character.name}</h3>
          <span className={`text-xs px-2 py-1 rounded ${typeColors[character.type]}`}>
            {character.type === 'character' ? '角色' :
             character.type === 'product' ? '商品' :
             character.type === 'environment' ? '環境' : '風格'}
          </span>
        </div>

        <p className="text-sm text-slate-600 dark:text-slate-400 mb-3 line-clamp-2">
          {character.description}
        </p>

        {character.ipProfile && (
          <div className="mb-3 flex flex-wrap gap-1.5">
            <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[11px] text-slate-700 dark:bg-slate-700 dark:text-slate-200">
              IP v{character.ipProfile.profileVersion}
            </span>
            <span className="rounded-full bg-blue-100 px-2 py-0.5 text-[11px] text-blue-700 dark:bg-blue-900/30 dark:text-blue-300">
              {character.ipProfile.strictIdentity ? '強一致' : '彈性一致'}
            </span>
            <span className="rounded-full bg-purple-100 px-2 py-0.5 text-[11px] text-purple-700 dark:bg-purple-900/30 dark:text-purple-300">
              {character.ipProfile.generationDefaults?.preferredVideoModel === 'seedance' ? 'Seedance' : 'Kling'} 預設
            </span>
          </div>
        )}

        {/* 標籤 */}
        {character.tags.length > 0 && (
          <div className="flex flex-wrap gap-1 mb-3">
            {character.tags.slice(0, 3).map(tag => (
              <span
                key={tag}
                className="text-xs px-2 py-0.5 bg-slate-100 dark:bg-slate-700
                         text-slate-600 dark:text-slate-300 rounded"
              >
                {tag}
              </span>
            ))}
            {character.tags.length > 3 && (
              <span className="text-xs text-slate-500">
                +{character.tags.length - 3}
              </span>
            )}
          </div>
        )}

        {/* 統計 */}
        <div className="flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
          <span>{character.views.length} 個視角</span>
          <span>使用 {character.usageCount} 次</span>
        </div>
      </div>
    </div>
  );
}
